apiVersion: v1
kind: ReplicationController
metadata:
  name: hadoop-slave
  labels:
    component: hadoop-slave
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: hadoop-slave
    spec:
      containers:
      - name: hadoop-slave
        image: vincentveracruz/hadoop-slave
        env:
        - name: RM_HOSTNAME
          value: <MASTER IP HERE>
        - name: HDFS_HOST
          value: <HDFS IP HERE>
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
      - name: storage
        emptyDir: {}
      - name: hadoop-slave