apiVersion: v1
kind: Service
metadata:
  name: sandbox
  labels:
    component: sandbox
spec:
  selector:
    component: sandbox
  ports:
  - name: clientprotocol
    port: 8088
    protocol: TCP
  - name: httpconnector
    port: 8042
    protocol: TCP
