apiVersion: v1
kind: ReplicationController
metadata:
  name: spark
  labels:
    component: spark
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: spark
    spec:
      containers:
      - name: spark
        image: sequenceiq/spark
        ports:
        - containerPort: 8088
          name: clientprotocol
          protocol: TCP
        - containerPort: 8042
          name: httpconnector
          protocol: TCP
      volumes:
      - name: storage
        emptyDir: {}