apiVersion: v1
kind: Service
metadata:
  name: spark
  labels:
    component: spark
spec:
  selector:
    component: spark
  ports:
  - name: clientprotocol
    port: 8088
    protocol: TCP
  - name: httpconnector
    port: 8042
    protocol: TCP